#!/usr/bin/env node
/**
 * Regenerate worker-configuration.d.ts for every package that has a wrangler.jsonc.
 *
 * Post-processing (so nobody hand-edits the generated file):
 * 1. Point every import of the gitignored .wrangler/validate/* build tree (`mainModule`, Durable
 *    Object namespaces) at ./src/* instead.
 * 2. Normalize the "Generated by Wrangler" banner (path args differ for --check).
 *
 * `--check` is non-mutating: it writes a sibling temp file, compares, and deletes it.
 */
import { spawnSync } from "node:child_process";
import { existsSync, readdirSync } from "node:fs";
import { readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packagesDir = join(root, "packages");
const checkOnly = process.argv.includes("--check");
const CHECK_BASENAME = "worker-configuration.check.d.ts";

function packageDirs(): string[] {
  return readdirSync(packagesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => join(packagesDir, entry.name))
    .filter((dir) => existsSync(join(dir, "wrangler.jsonc")))
    .toSorted();
}

function postprocess(text: string): string {
  return text
    .replace(
      /^\/\/ Generated by Wrangler by running `wrangler types[^`]*`/m,
      "// Generated by Wrangler by running `wrangler types`",
    )
    .replace(/import\("\.\/\.wrangler\/validate\/src\/([^"]+)"\)/g, 'import("./src/$1")')
    .replace(/[ \t]+$/gm, "");
}

async function generateOne(pkgDir: string): Promise<void> {
  const rel = relative(root, pkgDir);
  const typesPath = join(pkgDir, "worker-configuration.d.ts");
  // Kept under the package so mainModule paths match generate mode; --check never touches
  // worker-configuration.d.ts.
  const outPath = checkOnly ? join(pkgDir, CHECK_BASENAME) : typesPath;

  try {
    // Wrangler's bin is a Node script, so it is spawned under the current `node` without a shell.
    const wrangler = join(pkgDir, "node_modules", "wrangler", "bin", "wrangler.js");
    const result = spawnSync(process.execPath, [wrangler, "types", outPath], {
      cwd: pkgDir,
      encoding: "utf8",
    });
    if (result.error) {
      throw new Error(`could not run wrangler in ${rel}: ${result.error.message}`);
    }
    if (result.status !== 0) {
      console.error(result.stdout);
      console.error(result.stderr);
      throw new Error(`wrangler types failed in ${rel}`);
    }

    const next = postprocess(await readFile(outPath, "utf8"));
    if (checkOnly) {
      const before = await readFile(typesPath, "utf8").catch(() => null);
      if (before !== next) {
        throw new Error(
          `${rel}/worker-configuration.d.ts is out of date (run pnpm types:generate)`,
        );
      }
      console.log(`ok  ${rel}`);
      return;
    }
    await writeFile(typesPath, next);
    console.log(`gen ${rel}`);
  } finally {
    if (checkOnly) await rm(outPath, { force: true });
  }
}

const dirs = packageDirs();
if (dirs.length === 0) {
  console.error("no packages with wrangler.jsonc found");
  process.exit(1);
}

let failed = 0;
for (const dir of dirs) {
  try {
    await generateOne(dir);
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    failed++;
  }
}
if (failed) process.exit(1);
